spring:
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@localhost:1521/FREEPDB1}
    username: ${DB_USERNAME:hrms_user}
    password: ${DB_PASSWORD:hrms123}
    driver-class-name: ${DB_DRIVER:oracle.jdbc.OracleDriver}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true
    database-platform: ${HIBERNATE_DIALECT:org.hibernate.dialect.OracleDialect}

server:
  port: 8080
